[package]
name = "termy_terminal_ui"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
alacritty_terminal = { git = "https://github.com/alacritty/alacritty", rev = "4225cea231432fb23442b1da2463b4ec9dfd726c" }
flume = "0.11"
gpui = { git = "https://github.com/zed-industries/zed", package = "gpui" }
